using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Radzen;
using TaskManager.Client;
using Microsoft.AspNetCore.Components.Authorization;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Services.AddScoped<DialogService>();
builder.Services.AddScoped<NotificationService>();
builder.Services.AddScoped<TooltipService>();
builder.Services.AddScoped<ContextMenuService>();
builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddScoped<TaskManager.Client.TaskManagerDbService>();
builder.Services.AddAuthorizationCore();
builder.Services.AddHttpClient("TaskManager.Server", client => client.BaseAddress  = new Uri(builder.HostEnvironment.BaseAddress));
builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("TaskManager.Server"));
builder.Services.AddScoped<TaskManager.Client.SecurityService>();
builder.Services.AddScoped<AuthenticationStateProvider, TaskManager.Client.ApplicationAuthenticationStateProvider>();
var host = builder.Build();
await host.RunAsync();